### ISSUE TITLE
一些功能上的建议

### ISSUE THREAD

**Issue by fanchw** [dushixiang/kafka-map#11]
往kafka发送数据之后，主题详情页面需要手动刷新更新，希望能够得到响应后自动刷新。

**Comment by dushixiang** [comment]
> 往kafka发送数据之后，主题详情页面需要手动刷新更新，希望能够得到响应后自动刷新。

感谢建议，下个版本会进行调整。

**Comment by dushixiang** [comment]
1.1.0 版本已经进行了调整。
