### ISSUE TITLE
kakfa减少broken数量后查看topic接口报500

### ISSUE THREAD

**Issue by xuwentao00** [dushixiang/kafka-map#19]
创建kafka时设置的broken数量为8个，删减3后，查看topic，报错，请问下是什么原因。其他服务器通过IP+端口，用Kafka自带命令./kafka-topics.sh，可以查看到topci
![image](https://user-images.githubusercontent.com/58413893/137251270-2f84157b-b38c-4cf5-b2f8-bcc0cfe57ea1.png)
![image](https://user-images.githubusercontent.com/58413893/137251354-c02156f5-4d6f-45fc-8b9e-5190aa18c1e9.png)

**Comment by dushixiang** [comment]
看样子和 #21 问题一致，已修复此问题。
