### ISSUE TITLE
无法添加kafka集群

### ISSUE THREAD

**Issue by Pornfuck** [dushixiang/kafka-map#20]
![image](https://user-images.githubusercontent.com/29010836/137286397-1b2f73a2-80f0-4ec4-858d-721e7399824d.png)
请问是不是不支持带鉴权的kafka集群？

**Comment by dushixiang** [comment]
> ![image](https://user-images.githubusercontent.com/29010836/137286397-1b2f73a2-80f0-4ec4-858d-721e7399824d.png) 请问是不是不支持带鉴权的kafka集群？

目前不支持包含有认证功能的kafka，会在后续版本中增加。
