### ISSUE TITLE
源码直接运行网页404

### ISSUE THREAD

**Issue by zhangxinjian123** [dushixiang/kafka-map#22]
直接下载源码运行。网页http 直接404

**Comment by dushixiang** [comment]
> 直接下载源码运行。网页http 直接404

前端页面在 src/main/web 下面，使用 react 开发。

**Comment by zhangxinjian123** [comment]
那我打成jar 包直接java -jar  kafka-map-1.2.0  也不行。也是报404 这个该怎么解决呢？该怎么打jar 包呢？

**Comment by dushixiang** [comment]
> 那我打成jar 包直接java -jar kafka-map-1.2.0 也不行。也是报404 这个该怎么解决呢？该怎么打jar 包呢？

建议更新代码之后再执行，昨天我进行了修改。
打包命令是: mvn clean package -Dmaven.test.skip=true
你也可以使用 Dockerfile 进行打包。
