### ISSUE TITLE
如何隐藏一些前端功能

### ISSUE THREAD

**Issue by zhangxinjian123** [dushixiang/kafka-map#24]
前端比如我想隐藏topic的删除和alter 分区的功能，在哪里找。没源码里我找到，能告诉一下么？

**Comment by dushixiang** [comment]
> 前端比如我想隐藏topic的删除和alter 分区的功能，在哪里找。没源码里我找到，能告诉一下么？

此处即为删除topic的按钮 https://github.com/dushixiang/kafka-map/blob/master/src/main/web/src/components/Topic.js#L238
