### ISSUE TITLE
删除consumerGroup功能不可用，报错，提示错误不可见

### ISSUE THREAD

**Issue by ycj** [dushixiang/kafka-map#28]

**Comment by ycj** [comment]
![image](https://user-images.githubusercontent.com/1768377/147616649-b37eca91-5a61-4521-9930-87e55bd4d666.png)

**Comment by dushixiang** [comment]
> ![image](https://user-images.githubusercontent.com/1768377/147616649-b37eca91-5a61-4521-9930-87e55bd4d666.png)
> 
> 

删除topic 需要在配置中开启此功能

**Comment by ycj** [comment]
thank you!
