### ISSUE TITLE
建议添加的功能

### ISSUE THREAD

**Issue by unwenliu** [dushixiang/kafka-map#3]
首先感谢开发！
实际使用中还有以下几个需求感觉比较重要,因此提下建议哈

- 本项目在部署的时候没有HTTP认证，如果部署到公网上，比较危险。（当然了，谁没事不会闲着蛋疼把这个部署到公网上，但是我为了方便把家里的测试环境直接部署到ipv6公网了(*^_^*)，里面有测试的数据，还是挺危险的。）
- 能够实现类似kafka-manager的对单个topic的配置进行修改

**Comment by dushixiang** [comment]
> 首先感谢开发！
> 实际使用中还有以下几个需求感觉比较重要,因此提下建议哈
> 
> * 本项目在部署的时候没有HTTP认证，如果部署到公网上，比较危险。（当然了，谁没事不会闲着蛋疼把这个部署到公网上，但是我为了方便把家里的测试环境直接部署到ipv6公网了(_^_^_)，里面有测试的数据，还是挺危险的。）
> * 能够实现类似kafka-manager的对单个topic的配置进行修改

认证后面会增加的，topic的配置指的是基础属性那些吗？

**Comment by unwenliu** [comment]
对，修改单个topic的基础属性

**Comment by dushixiang** [comment]
v1.0.0 版本增加了认证功能。
