### ISSUE TITLE
连接报错

### ISSUE THREAD

**Issue by marshalby2** [dushixiang/kafka-map#31]
使用docker运行后，连接报错，信息如下:
`server 127.0.0.1:9092 can't connected.`
请问是为什么

**Comment by dushixiang** [comment]
> 使用docker运行后，连接报错，信息如下: `server 127.0.0.1:9092 can't connected.` 请问是为什么

docker 容器的网络环境是独立于宿主机器的，因此你无法使用 127.0.0.1 访问宿主机上的kafka。
