### ISSUE TITLE
delete consumer group failed 404

### ISSUE THREAD

**Issue by rikkartx** [dushixiang/kafka-map#37]
https://github.com/dushixiang/kafka-map/blob/04c9578fdefa0c3b0287cf0fe155a7601e88f982/src/main/web/src/components/ConsumerGroup.js#L88

should be `/consumerGroups` not `/consumerGroup`

**Comment by rikkartx** [comment]
https://github.com/dushixiang/kafka-map/blob/04c9578fdefa0c3b0287cf0fe155a7601e88f982/src/main/java/cn/typesafe/km/controller/ConsumerGroupController.java#L17

**Comment by dushixiang** [comment]
> Thanks for reporting the problem.

**Comment by rikkartx** [comment]
Thanks for your efforts🎉
