### ISSUE TITLE
一个页面小bug

### ISSUE THREAD

**Issue by wu1994a** [dushixiang/kafka-map#4]
主题管理页面，复选框点击效果都是全选
![image](https://user-images.githubusercontent.com/23646424/117266986-6187b100-ae88-11eb-92a7-56eeae5b1951.png)

**Comment by dushixiang** [comment]
v0.2.0版本增加了英文语言，并且已经去除了多选topic的功能。

**Comment by wu1994a** [comment]
确实，我只替换了kafka-map.jar，没删除数据库，删了数据库重新启动就好了

**Comment by dushixiang** [comment]
不用删除数据库的，重启就行。

**Comment by wu1994a** [comment]
不行，我直接解压覆盖，重新启动，不删除数据库还是旧版页面和功能

**Comment by wu1994a** [comment]
呃。。你说的没错，重启可以的。溜~~~
