### ISSUE TITLE
大神, 有个小问题,生产消息后再点开, ok按钮一直转圈

### ISSUE THREAD

**Issue by stromyin** [dushixiang/kafka-map#42]
![image](https://user-images.githubusercontent.com/22827779/178681532-62aecacf-9c48-4f47-bd1c-324688dc452d.png)
刷新页面后正常

**Comment by dushixiang** [comment]
> ![image](https://user-images.githubusercontent.com/22827779/178681532-62aecacf-9c48-4f47-bd1c-324688dc452d.png) 刷新页面后正常

收到，将在下个版本进行修复。
