### ISSUE TITLE
1.2.3版本 Consumer Group信息获取失败

### ISSUE THREAD

**Issue by zhangjianjian** [dushixiang/kafka-map#44]
![image](https://user-images.githubusercontent.com/11783987/182803644-97e7c3cb-10bd-42e5-82b0-c15eb2d17a0e.png)

**Comment by ycj** [comment]
![image](https://user-images.githubusercontent.com/1768377/202658611-49530ad4-a20b-41c8-ba1c-1c69af287040.png)
这个位置的消费组查看也不行

**Comment by dushixiang** [comment]
网络问题和kafka-map无关。
