### ISSUE TITLE
docker 部署无法修改登录用户与密码

### ISSUE THREAD

**Issue by ElvisWai** [dushixiang/kafka-map#45]
使用docker 方式部署，修改了DEFAULT_USERNAME   DEFAULT_PASSWORD  的值，但web仍以默认admin账号登录

**Comment by dushixiang** [comment]
> 使用docker 方式部署，修改了DEFAULT_USERNAME DEFAULT_PASSWORD 的值，但web仍以默认admin账号登录

只有在第一次启动的时候才可以设置，如果启动过可以将sqlite文件中user表的用户删除掉或者把整个sqlite文件删除，再次启动就会重新自动创建用户。

**Comment by ElvisWai** [comment]
好的，谢谢
