### ISSUE TITLE
KAFKA 3.2.3 不支持么？

### ISSUE THREAD

**Issue by starsliao** [dushixiang/kafka-map#46]
使用的KAFKA 3.2.3,  添加集群一直提示访问kafka broker节点超时,服务器到kafka的网络是正常的。

**Comment by starsliao** [comment]
解决了 KAFKA配置错了 。

**Comment by Jiar** [comment]
> 

遇到同样问题，可否提供下解决方案以供参考。😐

**Comment by Jiar** [comment]
> 解决了 KAFKA配置错了 。

@starsliao 
遇到同样问题，可否提供下解决方案以供参考。😐
