### ISSUE TITLE
copyright 年份可以不可以自动识别

### ISSUE THREAD

**Issue by dunhanson** [dushixiang/kafka-map#49]
现在是2022年，上面还是2021年

![](https://cdn-github.dunhanson.site/img/202211040958171.png)

**Comment by dushixiang** [comment]
> 现在是2022年，上面还是2021年
> 
> ![](https://camo.githubusercontent.com/0f11b28ee236d59633e111552ac551e5de191a794e95016c7411b416f21926e5/68747470733a2f2f63646e2d6769746875622e64756e68616e736f6e2e736974652f696d672f3230323231313034303935383137312e706e67)

这个不影响使用。
