### ISSUE TITLE
无法查看消费组

### ISSUE THREAD

**Issue by MouLv** [dushixiang/kafka-map#51]
在首页点击集群对应的消费组，触发访问接口为/consumerGroups?pageIndex=1&pageSize=10&clusterId=
提示访问kafka broker节点超时，接口返回504
<img width="385" alt="image" src="https://user-images.githubusercontent.com/16574475/206620091-4e4fa3da-ee9b-4ad8-b312-02ba5907b736.png">

添加了两个集群都是一样的报错，分别是阿里云kafka产品和自建的kafka集群。
使用docker启动，查看日志无异常输出

**Comment by yucesa** [comment]
也遇到相同的问题  cmak是可以看到的

**Comment by SuZhaoyang** [comment]
docker pull dushixiang/kafka-map部署，也有这个问题

**Comment by baixing99** [comment]
有谁解决了吗 我也是遇到了同样的问题

**Comment by dushixiang** [comment]
我使用原生安装的kafka和bitnami/kafka都没有复现这个问题。

**Comment by 2580cctk** [comment]
有谁解决了吗 我也是遇到了同样的问题

**Comment by 2580cctk** [comment]
kafka版本是2.3.0 (Commit:fc1aaa116b661c8a)
安装方式是直接下载安装包解压运行的




2541443935
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dushixiang/kafka-map"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月18日(星期二) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dushixiang/kafka-map] 无法查看消费组 (Issue #51)





  
有谁解决了吗 我也是遇到了同样的问题
  
请提供一下kafka 版本和安装方式，最好有安装脚本便于我进行测试，我自己安装的没问题。

**Comment by zddgg** [comment]
我也遇到这个问题，是消费组数量多导致获取信息超时，ConsumerGroupService.47，我测试环境消费组是18个

**Comment by baixing99** [comment]
有办法解决吗&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月19日(星期三) 中午11:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dushixiang/kafka-map] 无法查看消费组 (Issue #51)





 
我也遇到这个问题，是消费组数量多导致获取信息超时，ConsumerGroupService.47，我测试环境消费组是18个

**Comment by baixing99** [comment]
暂时我也没解决 反馈了 得到的回复是 他们没测出来 所以没办法解决
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月18日(星期二) 晚上6:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dushixiang/kafka-map] 无法查看消费组 (Issue #51)





 
有谁解决了吗 我也是遇到了同样的问题

**Comment by zddgg** [comment]
> 

我修改了两个配置，可以了。ClusterService.createAdminClient
        properties.put(AdminClientConfig.REQUEST_TIMEOUT_MS_CONFIG, "10000");
        properties.put(AdminClientConfig.RETRIES_CONFIG, "2");
我也不知道有没有其他影响。

**Comment by dushixiang** [comment]
> > 
> 
> 我修改了两个配置，可以了。ClusterService.createAdminClient properties.put(AdminClientConfig.REQUEST_TIMEOUT_MS_CONFIG, "10000"); properties.put(AdminClientConfig.RETRIES_CONFIG, "2"); 我也不知道有没有其他影响。

感谢提醒，我已经把这两个参数修改了，目前有其他人测试已修复此问题，v1.3.2 。
