### ISSUE TITLE
1.3.0 用jdk17 启动后 报404

### ISSUE THREAD

**Issue by yucesa** [dushixiang/kafka-map#52]
1.2.3 正常  本来是想看看修复消费组查看功能了没 新版直接用不了了
![image](https://user-images.githubusercontent.com/3981158/216260445-ba3a3d8a-b81f-4bd8-bacb-cad122a3f5f6.png)

**Comment by dushixiang** [comment]
> 1.2.3 正常 本来是想看看修复消费组查看功能了没 新版直接用不了了 ![image](https://user-images.githubusercontent.com/3981158/216260445-ba3a3d8a-b81f-4bd8-bacb-cad122a3f5f6.png)

由于打包脚本有误，导致了前端页面丢失，稍后即将修复。
