### ISSUE TITLE
拉取kafka较大的数据时网页奔溃、kafKa订阅的消费组无数据 实际是有数据的

### ISSUE THREAD

**Issue by chenshengshi** [dushixiang/kafka-map#57]
![image](https://user-images.githubusercontent.com/43060901/232650397-7b8beeef-ff89-4207-9d23-daa6440b5cb4.png)
![image](https://user-images.githubusercontent.com/43060901/232650493-20097e2c-4ab8-4546-a6d7-fcfa3534652b.png)
![image](https://user-images.githubusercontent.com/43060901/232650705-2caa022c-f87d-4fc2-91ed-42c9797042f7.png)

**Comment by dushixiang** [comment]
> ![image](https://user-images.githubusercontent.com/43060901/232650397-7b8beeef-ff89-4207-9d23-daa6440b5cb4.png)
> 
> ![image](https://user-images.githubusercontent.com/43060901/232650493-20097e2c-4ab8-4546-a6d7-fcfa3534652b.png)
> 
> ![image](https://user-images.githubusercontent.com/43060901/232650705-2caa022c-f87d-4fc2-91ed-42c9797042f7.png)
> 
> 

查询了多少条数据？

**Comment by chenshengshi** [comment]
一条数据7M，我知道数据比较大 只是pull 1条 
[数据格式.zip](https://github.com/dushixiang/kafka-map/files/11291503/default.zip)

**Comment by dushixiang** [comment]
> 一条数据7M，我知道数据比较大 只是pull 1条 [数据格式.zip](https://github.com/dushixiang/kafka-map/files/11291503/default.zip)

浏览器无法渲染出一个7M的文本的，所以没办法解决。
