### ISSUE TITLE
单条数据久7M kafkamap 因为数据过大 这个大小显示不准

### ISSUE THREAD

**Issue by chenshengshi** [dushixiang/kafka-map#59]
你好作者：我之前有反馈过单条数据过大 浏览器无法渲染的问题 ，这个您说没办法解决。。。关闭了。

![image](https://user-images.githubusercontent.com/43060901/236768601-763cdf4d-8e8e-4cb3-b3bc-1f081532cf14.png)
Pro_InstituteDataProviderDeviceInfo 这个topic单 个数据久7m 经过开发改造 处理Pro_InstituteDataProviderDeviceInfotopic数据输出到了Pro_InstituteKafkaData 这个topic中，我这个topic数据都100多M ，原始topic 不止4M 这个应该不准 这个有办法解决么

**Comment by dushixiang** [comment]
kafka 的日志存储是有压缩的，请参考：https://kafka.apache.org/documentation/#compaction
