### ISSUE TITLE
无法访问

### ISSUE THREAD

**Issue by jinjinxihuan** [dushixiang/kafka-map#6]
![image](https://user-images.githubusercontent.com/47840286/117523969-c0b30600-afed-11eb-95ec-cc2a790b90d7.png)

![image](https://user-images.githubusercontent.com/47840286/117523957-b5f87100-afed-11eb-9053-668eacc11874.png)
访问不到，是不是我的操作有问题呢？

**Comment by dushixiang** [comment]
前后端分离的项目，本地源码编译启动也需要启动前端，前端项目在 web 文件夹下。
