### ISSUE TITLE
M1芯片这个不行哦！

### ISSUE THREAD

**Issue by jsonMark** [dushixiang/kafka-map#61]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by dushixiang** [comment]
这个是web版本的，建议部署到服务器上，之后有时间搞一下 arm 版本或者做客户端了。

**Comment by jsonMark** [comment]
现在还只是本地测试。

**Comment by dushixiang** [comment]
已经在 v1.3.2 增加 arm架构的镜像。
