### ISSUE TITLE
kafka-map版本更新，hub镜像同步更新

### ISSUE THREAD

**Issue by liuxin638507** [dushixiang/kafka-map#62]
kafka-map版本更新，建议同步更新到docker hub仓库

**Comment by dushixiang** [comment]
忘记做自动触发了，目前已推送镜像，我之后改一下。

**Comment by liuxin638507** [comment]
> 忘记做自动触发了，目前已推送镜像，我之后改一下。
历史版本还是保留下吧，我现在pull latest版本,显示未Version:1.2.0，最新当前版本应该为1.3.1
![image](https://github.com/dushixiang/kafka-map/assets/32058132/4f59c446-fafd-4a26-9bca-c031818cd093)

**Comment by dushixiang** [comment]
应该是有缓存，之后更新我用tag做触发就可以指定版本号了。

**Comment by liuxin638507** [comment]
> 应该是有缓存，之后更新我用tag做触发就可以指定版本号了。
docker pull dushixiang/kafka-map:latest  还是 19 months ago
![image](https://github.com/dushixiang/kafka-map/assets/32058132/55e13c6e-153a-4e1d-86ba-fd58312a0bf0)

**Comment by liuxin638507** [comment]
> docker pull dushixiang/kafka-map:latest

确实是果用了国内的镜像加速原因，非常感谢！
