### ISSUE TITLE
org.apache.kafka.common.errors.RecordTooLargeException: The message is 17982136 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.

### ISSUE THREAD

**Issue by easayliu** [dushixiang/kafka-map#68]
我尝试添加启动参数-Dspring.kafka.producer.properties.max.request.size=10485760
但是仍然不生效，确定参数已经正常进去了
2023-09-15 03:24:11.307 INFO [ main] cn.typesafe.km.KafkaMapApplication : 10485760

**Comment by dushixiang** [comment]
> 我尝试添加启动参数-Dspring.kafka.producer.properties.max.request.size=10485760
> 
> 但是仍然不生效，确定参数已经正常进去了
> 
> 2023-09-15 03:24:11.307 INFO [ main] cn.typesafe.km.KafkaMapApplication : 10485760

如果你想修改kafka 客户端的参数，这样是修改不了的，因为配置是硬编码的。

**Comment by easayliu** [comment]
那我能在哪里修改呢。引入spring kafka配置来修改吗

**Comment by dushixiang** [comment]
> 那我能在哪里修改呢。引入spring kafka配置来修改吗
> 
> 

src/main/java/cn/typesafe/km/service/ClusterService.java
